FlightDataServices/FlightDataAnalyzer

analysis_engine/derived_parameters.py, tests/derived_parameters_test.py
This parameter shows the slope angle in degrees.
=> Add SlopeAngleToLanding

analysis_engine/plot_flight.py
Changed the opacity of Prepared.
https://developers.google.com/kml/documentation/kmlreference#color
first two characters are opacity. Added ff so that it is 100% opaque, i.e. solid.
Cheers,
Eron
=> Changed opacity of Prepared

analysis_engine/multistate_parameters.py
Changes were done by Rob on my comp
=> Change in logic to "Gear Up Selected" parameter

analysis_engine/key_point_values.py, tests/key_point_value_test.py
Please note that there's another pull request for FlightDataProfiles that is linked directly to this one: https://github.com/FlightDataServices/FlightDataProfiles/pull/3
=> Added new KPV from FCP profile - AltitudeInCruiseAverage

analysis_engine/key_point_values.py, tests/key_point_value_test.py
Changed Roll400To1000FtMax KPV to work for all flight phases instead of just for Initial Climb
=> (AE-1529) Changed Roll400To1000FtMax KPV to work for all flight phases

analysis_engine/key_point_values.py, tests/key_point_value_test.py
=> Ae 1523 mcp alt setting

analysis_engine/key_point_values.py, tests/key_point_value_test.py
Please  pull into the main repository
=> Engine derate and flex temp kp vs

analysis_engine/key_point_values.py, tests/key_point_value_test.py
AE-1597 is the correct Jira ticket - duplicate of AE-1588.
=> Ae 1588 737 touchdown acceleration with roll

analysis_engine/key_point_values.py, tests/key_point_value_test.py
plus tests.
Multiple KPVs are expected for this, but it was felt that some close together events could be seen as one event.
=> merge slices with kpvs if time between them is less than 10 seconds

analysis_engine/derived_parameters.py, analysis_engine/key_point_values.py, tests/derived_parameters_test.py, tests/key_point_value_test.py
plus tests. Requested by Herb Feller + Andy Robinshaw
=> New Embraer-specific KPV AccelerationNormalAboveWeightLimitAtTouchdown

analysis_engine/pre_processing/merge_parameters.py
Sorry, it looks a lot of changes but most are tidying up long lines and removing spaces.
It passes all unittests
=> AE-1743: Straighten Longitude before blending parameters

analysis_engine/key_point_values.py, tests/key_point_value_test.py
Acceleration Normal At Touchdown KPV
=> replace Acceleration Normal parameter with 

analysis_engine/key_point_values.py, tests/key_point_value_test.py
and includes bounces and touch and go
=> Roll Rate Above Max At Touchdown closer to actual touchdown 

analysis_engine/derived_parameters.py, analysis_engine/flight_phase.py, analysis_engine/key_point_values.py, analysis_engine/split_hdf_to_segments.py
Some regressions have recently been introduced on test. Several operators affected.
=> Ae 1979 fix regressions on test

analysis_engine/flight_phase.py
Please pull then reprocess sample TCAS RA events on Test.
=> AE-2113 TCAS minimum operating height increased from 360 to 900ft AAL.

analysis_engine/key_point_values.py, tests/key_point_value_test.py
Please check test program is OK - tests pass, but the code does not show correctly in my git tool.
=> Ae 2114 new tcas events for fdx

analysis_engine/key_point_values.py, tests/key_point_value_test.py
This implementation requires one less parameter and is a cleaner solution. It should behave the same as before, tests have been adjusted.
=> AE-2126: Better DHSelectedAt1500FtLVO implementation

analysis_engine/key_point_values.py, tests/key_point_value_test.py
Merging outdated pull requests to perform combined tests
=> Ae 2144 fuelcrossfeedvalve

analysis_engine/derived_parameters.py, analysis_engine/flight_phase.py, tests/derived_parameters_test.py, tests/flight_phase_test.py
First commit reverses previous attempt to manipulate Altitude AAL; second commit implements change to Bounced Landing flight phase.
=> Bugfix/ae 2533 a/dj/bounced landings

analysis_engine/key_point_values.py, tests/key_point_value_test.py
The thrust threshold changes to 79% for CRJ200ER (CL-600-2B19) models.
=> AE-2319 Fix Speedbrake Deployed With Power On Duration

analysis_engine/derived_parameters.py, tests/derived_parameters_test.py
This had been already approved. But I needed to rebase the branch onto master. So here is the new PR.
=> AE-2503 Fix AOA for CRJ-900

analysis_engine/derived_parameters.py, tests/derived_parameters_test.py
=> AE-2606 Use Baro Setting Selection where available

analysis_engine/key_point_values.py, tests/key_point_value_test.py
- RateOfClimbInRVSMAtHeightBeforeLevelFlight
- RateOfDescentInRVSMAtHeightBeforeLevelFlight
They are restricted to an altitude band between FL285 and FL415.
=> AE-2809 Creates 2 new KPVs

analysis_engine/key_point_values.py, analysis_engine/key_time_instances.py, tests/key_time_instance_test.py
* Increase moving average from 7 to 11 seconds.
* Filter out airspeed decreases right before flap retraction
=> AE-2583 Fine tune Climb Acceleration Start KTI
